imports:
    - { resource: config_dev.yml }

parameters:
    tile38_fleet_key: '%database_name%_test:fleet'
    tile38_doorstep_chan_namespace: '%database_name%_test'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        dbname:   "%database_name%_test"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://%redis_host%:6379/1
            options:
                prefix: "%database_name%_test:"

services:
    AppBundle\EventListener\CarbonListener:
        arguments:
            - '@snc_redis.default'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    AppBundle\Fixtures\AliceDataFixtures\SettingsProcessor:
        arguments:
          - '@coopcycle.settings_manager'
        tags:
            - { name: fidry_alice_data_fixtures.processor }
