api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh

oneup_uploader:
    resource: .
    type: uploader

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix:   '/api'

web:
    resource: '@AppBundle/Controller/'
    type:     'annotation'

nucleos_user_security:
    resource: "@NucleosUserBundle/Resources/config/routing/security.php"

nucleos_user_resetting:
    resource: "@NucleosUserBundle/Resources/config/routing/resetting.php"
    prefix: /resetting

nucleos_user_change_password:
    resource: "@NucleosUserBundle/Resources/config/routing/change_password.php"
    prefix: /security

nucleos_profile_profile:
    resource: "@NucleosProfileBundle/Resources/config/routing/profile.php"
    prefix: /profile

nucleos_profile_change_registration:
    resource: "@NucleosProfileBundle/Resources/config/routing/registration.php"
    prefix: /register

# Override NucleosProfileBundle route
nucleos_profile_profile_show:
    path:     /profile/
    methods:  [ GET, POST ]
    defaults:
        _controller: AppBundle\Controller\ProfileController::indexAction
        layout: 'profile.html.twig'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

coopcycle_admin:
    resource: '@AppBundle/Resources/config/routing/admin.yml'

coopcycle_dashboard:
    resource: '@AppBundle/Resources/config/routing/dashboard.yml'

coopcycle_profile:
    resource: '@AppBundle/Resources/config/routing/profile.yml'

oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
    prefix: /oauth2

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

foodtech_enabled_aware:
    resource: .
    type: foodtech_enabled_aware
